# Generated by Django 4.2.16 on 2026-03-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companytype_sector_remove_user_company_name_and_more'),
        ('core', '0002_remove_user_company_name'),
    ]

    operations = [
    ]
