# Generated by Django 4.2.16 on 2026-03-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0002_remove_user_company_name'),
        ('core', '0003_merge_20260301_1142'),
    ]

    operations = [
    ]
