# Generated by Django 5.2.7 on 2026-03-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
        ('core', '0005_merge_20260301_1516'),
    ]

    operations = [
    ]
