# Generated by Django 6.0.3 on 2026-03-08 09:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_0004_alter_user_email_0005_merge_20260301_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.college_image_path),
        ),
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.university_image_path),
        ),
    ]
