# Generated by Django 6.0.3 on 2026-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_college_image_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Governmental', 'حكومي'), ('External', 'شركات خارجية'), ('Proposed', 'مقترح')], default='Proposed', max_length=50),
        ),
    ]
