# Generated by Django 6.0.3 on 2026-03-08 11:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='Documentation_Path',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Logo',
        ),
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to=core.models.project_documentation_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Governmental', 'حكومي'), ('External', 'شركات خارجية'), ('Proposed', 'مقترح')], default='Proposed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.project_logo_path),
        ),
    ]
