# Generated by Django 6.0.3 on 2026-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_branch_project_college_project_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the college', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the university', null=True),
        ),
    ]
