# Generated by Django 6.0.3 on 2026-03-09 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_college_description_university_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupsupervisors",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisors",
                to="core.group",
            ),
        ),
    ]
