# Generated by Django 6.0.3 on 2026-03-10 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_groupsupervisors_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupsupervisors",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupsupervisors",
                to="core.group",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.branch",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.college",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.university",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
