# Generated by Django 6.0.3 on 2026-03-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_project_department_project_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrolled_at",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
