# Generated by Django 5.2.7 on 2026-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_graduation_year_alter_student_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
